/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as CheckinEmpIdRouteImport } from './routes/checkin.$empId'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSchedulingRouteImport } from './routes/_authenticated/scheduling'
import { Route as AuthenticatedSalariesRouteImport } from './routes/_authenticated/salaries'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProfitabilityRouteImport } from './routes/_authenticated/profitability'
import { Route as AuthenticatedPricingSimulatorRouteImport } from './routes/_authenticated/pricing-simulator'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckinEmpIdRoute = CheckinEmpIdRouteImport.update({
  id: '/checkin/$empId',
  path: '/checkin/$empId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulingRoute = AuthenticatedSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalariesRoute = AuthenticatedSalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfitabilityRoute =
  AuthenticatedProfitabilityRouteImport.update({
    id: '/profitability',
    path: '/profitability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPricingSimulatorRoute =
  AuthenticatedPricingSimulatorRouteImport.update({
    id: '/pricing-simulator',
    path: '/pricing-simulator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pricing-simulator': typeof AuthenticatedPricingSimulatorRoute
  '/profitability': typeof AuthenticatedProfitabilityRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/salaries': typeof AuthenticatedSalariesRoute
  '/scheduling': typeof AuthenticatedSchedulingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/checkin/$empId': typeof CheckinEmpIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pricing-simulator': typeof AuthenticatedPricingSimulatorRoute
  '/profitability': typeof AuthenticatedProfitabilityRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/salaries': typeof AuthenticatedSalariesRoute
  '/scheduling': typeof AuthenticatedSchedulingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/checkin/$empId': typeof CheckinEmpIdRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/pricing-simulator': typeof AuthenticatedPricingSimulatorRoute
  '/_authenticated/profitability': typeof AuthenticatedProfitabilityRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/salaries': typeof AuthenticatedSalariesRoute
  '/_authenticated/scheduling': typeof AuthenticatedSchedulingRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/checkin/$empId': typeof CheckinEmpIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity-log'
    | '/attendance'
    | '/clients'
    | '/employees'
    | '/materials'
    | '/payments'
    | '/pricing-simulator'
    | '/profitability'
    | '/projects'
    | '/salaries'
    | '/scheduling'
    | '/users'
    | '/checkin/$empId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/activity-log'
    | '/attendance'
    | '/clients'
    | '/employees'
    | '/materials'
    | '/payments'
    | '/pricing-simulator'
    | '/profitability'
    | '/projects'
    | '/salaries'
    | '/scheduling'
    | '/users'
    | '/checkin/$empId'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity-log'
    | '/_authenticated/attendance'
    | '/_authenticated/clients'
    | '/_authenticated/employees'
    | '/_authenticated/materials'
    | '/_authenticated/payments'
    | '/_authenticated/pricing-simulator'
    | '/_authenticated/profitability'
    | '/_authenticated/projects'
    | '/_authenticated/salaries'
    | '/_authenticated/scheduling'
    | '/_authenticated/users'
    | '/checkin/$empId'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckinEmpIdRoute: typeof CheckinEmpIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkin/$empId': {
      id: '/checkin/$empId'
      path: '/checkin/$empId'
      fullPath: '/checkin/$empId'
      preLoaderRoute: typeof CheckinEmpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling': {
      id: '/_authenticated/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof AuthenticatedSchedulingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salaries': {
      id: '/_authenticated/salaries'
      path: '/salaries'
      fullPath: '/salaries'
      preLoaderRoute: typeof AuthenticatedSalariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profitability': {
      id: '/_authenticated/profitability'
      path: '/profitability'
      fullPath: '/profitability'
      preLoaderRoute: typeof AuthenticatedProfitabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing-simulator': {
      id: '/_authenticated/pricing-simulator'
      path: '/pricing-simulator'
      fullPath: '/pricing-simulator'
      preLoaderRoute: typeof AuthenticatedPricingSimulatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPricingSimulatorRoute: typeof AuthenticatedPricingSimulatorRoute
  AuthenticatedProfitabilityRoute: typeof AuthenticatedProfitabilityRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSalariesRoute: typeof AuthenticatedSalariesRoute
  AuthenticatedSchedulingRoute: typeof AuthenticatedSchedulingRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPricingSimulatorRoute: AuthenticatedPricingSimulatorRoute,
  AuthenticatedProfitabilityRoute: AuthenticatedProfitabilityRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSalariesRoute: AuthenticatedSalariesRoute,
  AuthenticatedSchedulingRoute: AuthenticatedSchedulingRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckinEmpIdRoute: CheckinEmpIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
